version: '3'
services:
  mageai:
    image: mageai/mageai:latest
    build:
      context: .
    command: mage start apu_data_pipeline
    environment:
      - ENV=dev
    ports:
      - 6789:6789
    volumes:
      - .:/home/src
      # - .:/home/src/apu_data_pipeline/io_config.yaml
    restart: on-failure:5
    stdin_open: true #used for interactive debugging
    tty: true #u sed for interactive debugging
