version: '3.8'

services:
  mageai:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - dev.env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - "6789:6789"
    volumes:
      - ./apu_data_pipeline:/home/src/apu_data_pipeline
      - ./io_config.yaml:/home/src/apu_data_pipeline/io_config.yaml
      - ~/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
    restart: on-failure:5
