version: '3.8'

services:
  mage_ai:
    image: mageai/mageai:latest
    container_name: mage_ai_container
    ports:
      - "6789:6789"
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=your_account_name
      - AZURE_STORAGE_ACCOUNT_KEY=your_account_key
    volumes:
      - ./data:/app/data
      - ./utils:/app/utils
      - ./mage:/home/src/mage
    command: ["mage", "start", "apu_data_pipeline"]
