version: '3.8'
services:
  apu_data_pipeline:
    build: .
    ports:
      - "6789:6789"
    dns:
      - 172.31.0.8
    volumes:
      - ./mage_data:/app/data
      - ./:/home/src/apu_data_pipeline
    environment:
      - USER_CODE_PATH=/home/src/apu_data_pipeline
    command: ["mage", "start", "--project", "apu_data_pipeline"]
    restart: always
