version: 0.1.1
default:
  MSSQL_DATABASE: 172.31.0.112
  MSSQL_SCHEMA: TestDb
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: APU-VM047
  MSSQL_PORT: 1433
  MSSQL_USER: sa-dwh
  MSSQL_PASSWORD: 40v4A&WuP6$5

  ORACLE_DATABASE: 172.31.0.133
  ORACLE_SCHEMA: orcl
  ORACLE_HOST: 172.31.0.133
  ORACLE_PORT: 1521
  ORACLE_USER: DWH
  ORACLE_PASSWORD: Pass1231
