version: 0.1.1
default:
  MSSQL_DATABASE: mage_db
  MSSQL_SCHEMA: dbo
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: APU-VM047.apu.mn
  MSSQL_PORT: 1433
  MSSQL_USER: mage_user
  MSSQL_PASSWORD: Asuult123456
