version: 0.1.1

mssql_dwh_LandingDb_Python:
  MSSQL_DATABASE: LandingDb
  MSSQL_SCHEMA: Python
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: 172.31.0.112
  MSSQL_PORT: 1433
  MSSQL_USER: sa-dwh
  MSSQL_PASSWORD: 40v4A&WuP6$5

mssql_dwh_TestDb_Manual:
  MSSQL_DATABASE: TestDb
  MSSQL_SCHEMA: Manual
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: 172.31.0.112
  MSSQL_PORT: 1433
  MSSQL_USER: sa-dwh
  MSSQL_PASSWORD: 40v4A&WuP6$5

oracle_greenerp:
  ORACLE_HOST: 172.31.0.133
  ORACLE_PORT: 1521
  ORACLE_SERVICE_NAME: ORCL
  ORACLE_USER: ERP_WH
  ORACLE_PASSWORD: wh_green
  ORACLE_DRIVER: "oracle"